config/routes.rb
Rails.application.routes.draw do
  resources :tracks
  devise_for :users
  resources :pages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/track.rb
class Track < ApplicationRecord

  belongs_to :user

    has_attached_file :image, styles: { medium: "400x400#", small: "200x200#" }
    validates_attachment :image, content_type:  { content_type: [/\Aimage\/.*\z/] }

    has_attached_file :mp3
    validates_attachment :mp3, content_type: { content_type: ["audio/mpeg", "audio/mp3"] }, file_name: { matches: [/mp3\z/] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, authentication_keys: {email: true, login: false}

  has_many :tracks



  attr_accessor :login

validate :validate_username

  validates :username,
    presence: true,
    uniqueness: { case_sensitive: false }

    def login=(login)
      @login = login
    end

    def login
      @login || self.username || self.email
    end


    def validate_username
      if User.where(email: username).exists?
        errors.add(:username, :invalid)
      end
    end


    def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(username) = :value OR lower(email) = :value", { value: login.downcase }]).first
      else
        if conditions[:username].nil?
          where(conditions).first
        else
          where(username: conditions[:username]).first
        end
      end
    end
end



def login=(login)
  @login = login
end

def login
  @login || self.username || self.email
end


def validate_username
  if User.where(email: username).exists?
    errors.add(:username, :invalid)
  end
end


def self.find_first_by_auth_conditions(warden_conditions)
  conditions = warden_conditions.dup
  if login = conditions.delete(:login)
    where(conditions).where(["lower(username) = :value OR lower(email) = :value", { value: login.downcase }]).first
  else
    if conditions[:username].nil?
      where(conditions).first
    else
      where(username: conditions[:username]).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @tracks = Track.all
  end

  def show
  end


  def new
    @track = current_user.tracks.build
  end

  def edit
  end


  def create
    @track = current_user.tracks.build(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_path, notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_track
      @track = Track.find(params[:id])
    end


    def track_params
      params.require(:track).permit(:artist, :album, :song, :genre, :year, :image, :mp3, :ogg)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name

    :user

  end

  def resource

    @resource ||= User.new

  end

  def devise_mapping

    @devise_mapping ||= Devise.mappings[:user]

  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/_header.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">

            <% if user_signed_in? %>
            <a class="navbar-brand">
                <%= link_to "Bayside Vinyl", pages_path, class: "navbar-brand" %>
            </a>
        <% else %>
            <a class="navbar-brand"></li><%= link_to "Bayside Vinyl", pages_path, class: "navbar-brand" %>
        </a>
        <% end %>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bvoptions" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bvoptions">
        <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li><%= link_to current_user.username, edit_user_registration_path, class: "active" %></li>
            <li><%= link_to "Tracks", tracks_path, class: "active" %></li>
        <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
            <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
            <li><%= link_to "BV Collection", tracks_path, class: "active" %></li>
            <% end %>
        </ul>
    </div>
    <!-- /.navbar-collapse -->
    <!-- /.navbar-collapse -->

</div>
<!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="Maurice Murphy">
        <%= favicon_link_tag 'BVicon.png' %>

        <title>Bayside Vinyl</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <%= render 'layouts/header' %>
        <% flash.each do |name, msg| %>
        <% content_tag(:div, msg, class: "alert alert-info") %>
        <% end %>
        <%= yield %>
    </body>

    <!-- Bootstrap core JavaScript
================================================== -->
    <!-- jQuery -->
    <script
			  src="https://code.jquery.com/jquery-3.2.1.min.js"
			  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
			  crossorigin="anonymous"></script>
		<%= javascript_include_tag 'jquery.jplayer' %>
</html>

app/views/pages/index.html.erb
<header class="intro">
     <div class="intro-body">
         <div class="container">
             <div class="row">
                 <div class="col-xs-8 col-xs-offset-2">
                     <img class="logo-heading"><%= image_tag("Bayside Logo.svg", alt: "logo-img", height: 720, width: 720) %></img>
                 </div>
                 <% if user_signed_in? %>
                 <div class="jumbotron">
                 <h1 class="Hi">Welcome Back!</h1>
                 <p class="lead">We are glad to have you back to Bayside Vinyl, <%= current_user.username %>. As always, we are looking to change your idea of vinyl record shopping. </p>
                 <hr class="my-4">
                 <p class="greetmessage2">You can edit your profile by simply clicking on your profile name the navigation bar at the top of the page.</p>
               </div>
               <% else %>
               <div class="jumbotron">
               <h1 class="Hi">Welcome!</h1>
               <p class="lead">We are Bayside Vinyl and we are looking to change your idea of vinyl record shopping.</p>
               <hr class="my-4">
               <p class="greetmessage2">You can sign in and/or sign up at the top of this page. You can also go directly to the BV Collection (media player) with the play button down below (or the tracks link at the top of this page). There are no requirements to play the tracks. However, you do need to sign in/sign up to add them to the player.</p>
             </div>
               <% end %>
             </div>
         </div>
     </div>
</header>




<div class="container">

  <!-- For heading -->
  <div class="row">

  </div><!-- /.row -->




<!-- BV mp3 app -->
<div class="row featurette">
  <div class="col-md-7 col-md-push-5">
    <h2 class="featurette-heading">Looking for a particular record, but not sure which one to chose? <span class="text-muted">Well, perhaps you could gain some inspiration by pressing this play.</span></h2>
    <p class="homeparagraph"></p>

  </div>
  <div class="Error: source does not appear to be markup.">
  <div class="col-md-5 col-md-pull-7">
     <a href="tracks#index">
     <img class="featurette-image img-responsive center-block"><%= image_tag("BVplay.svg", alt: "square2-img", height: 500, width: 500) %></img>
   </a>
   </div>
 </div>
 </div>




  <!-- START THE FEATURETTES -->

  <hr class="featurette-divider">

  <div class="page-header">
    <h2 class="featurette-heading">Frequently Asked Questions: </h2>
  </div>

  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading">What is Bayside Vinyl? <span class="text-muted">It's a proposed record store for the Brickell (Downtown Miami) area.</span></h2>

      <p class="homeparagraph">Bayside Vinyl is an idea that I have had for about 8 years now. I picked up an affinity for vinyl records through my love for sample-based music.
                               There are not many record stores in Miami and certainly not the Downtown/Brickell area. I would love to have the opportunity to change that.</p>
    </div>
    <div class="homepagepic">
    <div class="col-md-5">
      <img class="featurette-image img-responsive center-block"><%= image_tag("Brickellvinyl.jpg", alt: "square1-img", height: 500, width: 500) %></img>
    </div>
  </div>
  </div>

  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7 col-md-push-5">
      <h2 class="featurette-heading">Why Brickell City Centre? <span class="text-muted">It's the newest mall in the area and it is adding new stores everyday.</span></h2>
      <p class="homeparagraph">The experience of going into a store and buying physical copies of
        various forms of media has changed. People are more likely to just stream their content. However, vinyl has consistently had a <a class="linkvinyl" href="http://consequenceofsound.net/2017/01/vinyl-on-track-to-become-a-billion-dollar-industry-in-2017/">yearly resurgence</a>.
        In fact, there are even <a class="linkvinyl" href="http://thevinylfactory.com/features/the-8-best-vinyl-subscription-services-to-help-grow-your-record-collection/">subscription services</a> for vinyl now.
        The idea of actually having a modern day record store is what drew me to Brickell City Centre. There is no better time to dive into the world of vinyl than right now for both collectors and sellers.</p>

    </div>
    <div class="homepagepic">
    <div class="col-md-5 col-md-pull-7">
      <img class="featurette-image img-responsive center-block"><%= image_tag("Brickell.jpg", alt: "square2-img", height: 500, width: 500) %></img>
    </div>
  </div>
  </div>

  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading">Are there anymore plans for Bayside Vinyl? <span class="text-muted">Yes.</span></h2>
      <p class="homeparagraph">Well, this page actually serves as the central hub for anything connected to the Bayside Vinyl brand.
                               As of right now, the BV Music Player is available to use. The goal is to create possibly a blog, as well as, a vinyl selection assistant app.
                               The vinyl selection app is called Hit-or-Miss. With the combination of the Discogs api and Ruby on Rails, Hit-or-Miss will revolutionize the digital vinyl record shopping experience.
                               So to answer the question, there absolutely plans to expand the brand. </p>
    </div>
    <div class="homepagepic">
    <div class="col-md-5">
      <img class="featurette-image img-responsive center-block"><%= image_tag("Content.jpg", alt: "square3-img", height: 500, width: 500) %></img>
    </div>
  </div>
  </div>

  <hr class="featurette-divider">

  <!-- /END THE FEATURETTES -->

  <footer class="footer">
     <div class="container">
       <span class="text-muted"><a href="https://github.com/murphym757/baysidevinyl"><%= image_tag("github.png", alt: "png-img", height: 100, width: 180) %></a>
         <a href="https://mauricemurphyjr.herokuapp.com"><%= image_tag("mmlogo.png", alt: "png-img", height: 80, width: 160) %></a><br>Copyright &copy; 2017<br></span>
     </div>
</footer>

</div><!-- /.container -->

app/views/tracks/_form.html.erb
<%= bootstrap_form_for @track, html: { multipart: true } do |f| %>
<% if @track.errors.any? %>
<div id="error_explanation">
    <h2 class="page-title"><%= pluralize(track.errors.count, "error") %>
        prohibited this track from being saved:</h2>

    <ul>
        <% track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="container">
    <header class="formpage">
        <div class="row">
                <div class="newTrackForm">
                    <div class="panel panel-default">
                        <div class="panel-heading">New Track</div>
                    </div>
                    <div class="panel-body">
                        <div class="field">
                            <%= f.text_field :artist, autofocus: true, placeholder: "Enter Artist" %>
                        </div>

                        <div class="field">
                            <%= f.text_field :album, autofocus: true, placeholder: "Enter Album"  %>
                        </div>

                        <div class="field">
                            <%= f.text_field :song, autofocus: true, placeholder: "Enter Song"  %>
                        </div>

                        <div class="field">
                            <%= f.text_field :genre, autofocus: true, placeholder: "Enter Genre"  %>
                        </div>

                        <div class="field">
                            <%= f.text_field :year, autofocus: true, placeholder: "Enter Year"  %>
                        </div>

                        <div class="field">
                            <%= f.file_field :image, autofocus: true  %>
                        </div>

                        <div class="field">
                            <%= f.file_field :mp3, autofocus: true  %>
                        </div>

                        <div class="actions">
                            <%= f.submit "Update Track", class: "btn btn-custom"%>
                        </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </header>
    </div>

app/views/tracks/edit.html.erb
<div class="container">
    <header class="formpage">
        <div class="row">
          <div class="panel-body">
                <img class="logo-heading-form2">
                    <%= image_tag @track.image.url(:medium) %>
                </img>
            </header>
            <div class="panel-body">
            <%= render 'form', track: @track %>
                <%= button_to "Delete Track", track_path(@track), data: { confirm: "Are you sure that you to delete this track?" }, method: :delete, class: "btn btn-custom" %>
            </div>
        </div>
    </div>
  </header>
</div>

app/views/tracks/index.html.erb
<div class="intro-index">
    <div class="container">
              <%= image_tag("BV Collection.svg", alt: "square2-img", height: 500, width: 500) %>
              <div class="row">
                  <% @tracks.each do |track| %>
                  <div class="col-xs-6 col-sm-3 col-md-3 col-lg-3">
                      <div class="rounded">
                          <%= link_to (image_tag track.image.url(:medium), class: 'image'), track %>
                      </div>
                  </div>
                  <% end %>
              </div>
              <% if user_signed_in? %>
              <div class="jumbotron">
                  <p class="lead">We are glad to have you back to Bayside Vinyl,
                      <%= current_user.username %>. As always, we are looking to change your idea of vinyl record shopping.
                  </p>
                  <hr class="my-4">
                  <h2 class="featurette-heading">Helpful Tips:</h2>
                  <p class="helpfultips">
                      <ol>
                          <li>Please refresh the page once you have selected a track. This refreshes the page, as well as, the media player itself.</li>
                          <br>
                          <li>Some MP3s will not upload based on their format. I personally recommend the file converter,
                              <a class="linkvinyl" href="https://macroplant.com/adapter/">Adapter</a>. It's free and easy to use.</li>
                          <br>
                          <li>If the play button isn't visible initially (via mobile), simply scroll down the page.</li>
                      </ol>
                  </p>
                  <hr class="my-4">
              <li>
                  <%= button_to "New Track", new_track_path, method: :get, class: "btn btn-custom" %>
              </li>
          </div>
      <% else %>
          <div class="jumbotron">
              <hr class="my-4">
              <h2 class="featurette-heading">Helpful Tips:</h2>
              <p class="helpfultips">
                  <ol>
                      <li>Please refresh the page once you have selected a track. This refreshes the page, as well as, the media player itself.</li>
                      <br>
                      <li>Some MP3s will not upload based on their format. I personally recommend the file converter,
                          <a class="linkvinyl" href="https://macroplant.com/adapter/">Adapter</a>. It's free and easy to use.</li>
                      <br>
                      <li>If the play button isn't visible initially (via mobile), simply scroll down the page.</li>
                  </ol>
              </p>
              <hr class="my-4">
          <li>
              <%= button_to "New Track", new_user_session_path, class: "btn btn-custom" %>
          </li>
      </div>
    </div>
  <% end %>
</div>

app/views/tracks/new.html.erb
<%= render 'form', track: @track %>

<div class="container">
    <header class="formpage">
        <div class="row">
            <%= link_to 'Back', tracks_path %>
        </div>
    </header>
</div>

app/views/tracks/show.html.erb
<div class="intro-body2">
    <div class="container">
        <div class="row">
        <li class="showcontents">
            <div class="col-xs-12 col-md-12 col-lg-12">
                <%= image_tag @track.image.url(:medium), class: :albumart, size: "250x250"%>
                <% if user_signed_in? %>
                <%= button_to "Edit", edit_track_path(@track), method: :get, class: "btn btn-custom" %>
            <% else %>
                <% end %>
            </div>
        </li>

        <li class="showcontents2">
            <div class="col-xs-12 col-md-12 col-lg-12">
                <div class="trackinfo">
                    <p>
                        <h2 class="featurette-heading2">
                            <strong>Artist:</strong>
                            <span class="text-muted">
                                <%= @track.artist %>
                            </span>
                        </h2>
                    </p>

                    <p>
                        <h2 class="featurette-heading2">
                            <strong>Album:</strong>
                            <span class="text-muted">
                                <%= @track.album %>
                            </span>
                        </h2>
                    </p>

                    <p>
                        <h2 class="featurette-heading2">
                            <strong>Song:</strong>
                            <span class="text-muted">
                                <%= @track.song %>
                            </span>
                        </h2>
                    </p>

                    <p>
                        <h2 class="featurette-heading2">
                            <strong>Genre:</strong>
                            <span class="text-muted">
                                <%= @track.genre %>
                            </span>
                        </h2>
                    </p>

                    <p>
                        <h2 class="featurette-heading2">
                            <strong>Year:</strong>
                            <span class="text-muted">
                                <%= @track.year %>
                            </span>
                        </h2>
                    </p>

                    <p>
                        <h2 class="featurette-heading2">
                            <strong>Post Creator:</strong>
                            <span class="text-muted">
                                <%= @track.user.username %>
                            </span>
                        </h2>
                    </p>
                </div>
            </div>
        </li>
    </div>

    <div id="jquery_jplayer_1" class="jp-jplayer"></div>
    <div id="jp_container_1" class="jp-audio">
        <div class="jp-type-single">
            <div class="jp-gui jp-interface">
                <ul class="jp-controls">
                    <li>
                        <a href="javascript:;" class="jp-play" tabindex="1">&#61515;</a>
                    </li>
                    <li>
                        <a href="javascript:;" class="jp-pause" tabindex="1">&#61516;</a>
                    </li>
                    <li>
                        <a href="javascript:;" class="jp-mute" tabindex="1" title="mute">&#61480;</a>
                    </li>
                    <li>
                        <a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">&#61478;</a>
                    </li>
                </ul>

                <div class="jp-progress">
                    <div class="jp-seek-bar">
                        <div class="jp-play-bar"></div>
                    </div>
                </div>

                <div class="jp-time-holder">
                    <div class="jp-current-time"></div>
                </div>

                <div class="jp-volume-bar">
                    <div class="jp-volume-bar-value"></div>
                </div>

                <div class="jp-no-solution">
                    <span>Update Required</span>
                    Please refresh the page.
                </div>
            </div>
        </div>
    </div>
</div>
</div>

<script>
$(document).ready(function () {
    $("#jquery_jplayer_1").jPlayer({
        ready: function () {
            $(this).jPlayer("setMedia", {
                mp3: "<%= @track.mp3.url %>"
            });
        },
        swfPath: "/js",
        supplied: "mp3"
    });
});
</script>

<div class="modal fade" id="trackShowModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">(<%= @track.song %>)</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body">
            <%= render "tracks/form" %>
        </div>
        <div class="modal-footer"></div>
    </div>
</div>
</div>